export const EARTH_RADIUS_KM = 6371;

export const DEFAULT_PAGE_SIZE = 20;
export const MAX_PAGE_SIZE = 100;

export const MIN_STOCK_QUANTITY = 0;

export const ORDER_NUMBER_PREFIX = "ORD";

export const TRANSPORT_BUFFER_PERCENTAGE = 0.1;

export const ROLES = {
  MANAGER: "MANAGER",
  RAW_STOCK_MANAGER: "RAW_STOCK_MANAGER",
  PRODUCTION_CLIENT: "PRODUCTION_CLIENT",
  DISTRIBUTOR: "DISTRIBUTOR",
  TRANSPORT_PROVIDER: "TRANSPORT_PROVIDER",
  FINISHED_STOCK_MANAGER: "FINISHED_STOCK_MANAGER",
} as const;

export const ORDER_TYPES = {
  RAW_MATERIAL_ORDER: "RAW_MATERIAL_ORDER",
  FINISHED_PRODUCT_ORDER: "FINISHED_PRODUCT_ORDER",
  DELIVERY: "DELIVERY",
} as const;

export const ORDER_STATUSES = {
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  PREPARING: "PREPARING",
  IN_TRANSIT: "IN_TRANSIT",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
} as const;

export const VEHICLE_STATUSES = {
  AVAILABLE: "AVAILABLE",
  IN_USE: "IN_USE",
  MAINTENANCE: "MAINTENANCE",
  INACTIVE: "INACTIVE",
} as const;
